# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activeadmin-dropzone"
  s.version = "0.2.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maxim Gladkov Alexey Krylov"]
  s.date = "2016-02-08"
  s.email = "contact@maximgladkov.com alexey2142@mail.ru"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = Dir["{app,config,db,lib}/**/*", "Rakefile", "README.md"]
  s.homepage = "http://maximgladkov.com/blog/activeadmin-dropzone-gem"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Easy to use integration of drag&drop files upload via dropzone.js for ActiveAdmin"
  s.add_dependency "jeweler", ">= 0"
  s.add_development_dependency 'rspec-rails', '3.1.0'
  s.add_development_dependency 'simplecov', '0.11.1'
end
